# Generated by Django 6.1 on 2026-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('character', 'Character voice'), ('narrator', 'Narrator voice')], default='character', max_length=20)),
                ('provider', models.CharField(default='chatterbox', max_length=50)),
                ('provider_voice_id', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='e.g. tone, pitch, accent notes')),
                ('sample_audio', models.FileField(blank=True, null=True, upload_to='voice_samples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
