# Generated by Django 6.1 on 2026-08-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Detailed features: appearance, build, clothing, personality, mannerisms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice', models.ForeignKey(blank=True, limit_choices_to={'role': 'character'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='voices.voice')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='character_references/')),
                ('label', models.CharField(blank=True, help_text="e.g. 'front view', 'three-quarter'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='characters.character')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
