# Generated by Django 6.1 on 2026-08-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('storyline', models.TextField(help_text='Your free-form storyline/synopsis for the episode')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scripted', 'Script submitted'), ('generating', 'Generating'), ('assembling', 'Assembling final video'), ('complete', 'Complete'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('final_video', models.FileField(blank=True, null=True, upload_to='final_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='dialogue_audio/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='characters.character')),
            ],
            options={
                'ordering': ['panel', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position of this panel within the episode')),
                ('action_description', models.TextField(blank=True, help_text='Narration text describing what happens in this panel')),
                ('image_prompt_notes', models.TextField(blank=True, help_text='Extra prompt guidance for the image model (camera angle, framing, etc.)')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated_panels/')),
                ('narration_audio', models.FileField(blank=True, null=True, upload_to='narration_audio/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('image_queued', 'Image queued'), ('image_ready', 'Image ready'), ('audio_queued', 'Audio queued'), ('audio_ready', 'Audio ready'), ('ready', 'Ready for assembly'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('characters', models.ManyToManyField(blank=True, related_name='panels', to='characters.character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='episodes.episode')),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='scenes.scene')),
            ],
            options={
                'ordering': ['episode', 'order'],
                'unique_together': {('episode', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('image', 'Image generation'), ('voice', 'Voice generation'), ('assembly', 'Video assembly')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, help_text="e.g. 'flux2', 'chatterbox'", max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dialogue_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='episodes.dialogueline')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='episodes.episode')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='episodes.panel')),
            ],
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='episodes.panel'),
        ),
    ]
